FROM kdvolder/jdk8
VOLUME /tmp
ADD springcloud-eureka-server-2.0.3.RELEASE.jar app.jar
#RUN bash -c 'touch /app.jar'
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
EXPOSE 8761